use_frameworks!

platform :ios, '9.0'

target 'YHTabBar_Example' do
  pod 'YHTabBar', :path => '../'

  target 'YHTabBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
